version: '3.8'

services:
  aws:
    image: localstack/localstack:1.2.0
    container_name: awslocal
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.volumes/localstack:/var/lib/localstack"